### ISSUE TITLE
Code Problem

### ISSUE THREAD

**Issue by wangjsj33** [qiumuyang/SIAB#1]
Hello, thank you for sharing your work. An error occurred in evaluate_metrics in your code. It seems that you did not provide medpy.metric.binary. I tried to add the implementation of medpy.metric.binary. But in evaluate_metrics, is there an extra assd in the line dist_metric = ["asd", "assd", "hd"]? I tried to test and got an error TypeError: dc() missing 1 required positional argument: 'gt'

**Comment by qiumuyang** [comment]
Hi wangjsj33,

Thank you for bringing this to our attention. We have fixed the problem by adding the missing `medpy` dependency to `env.yml`.

To resolve the problem, please recreate your virtual environment or patch your current environment by running the following command:
```bash
conda install bioconda::medpy conda-forge::simpleitk
```

Best regards.
